### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dentex** [heavyplayer/tooltip#1]
Hello.
I forked the project and made some changes.
I would like to add a `LICENSE.txt`.
Is OK for you the [MIT license](http://opensource.org/licenses/MIT), with on top

```
Copyright (c) 2014 Gonçalo Silva & João Martins Costa
```

?

Thanks.

**Comment by goncalossilva** [comment]
Both that and `Copyright (c) 2014 Heavy Player` would be okay.

Thanks!

**Comment by dentex** [comment]
OK thanks.

**Comment by dentex** [comment]
Done. 

(almost forgot...)   :)
